#!/bin/bash
# sudo wget -O - https://raw.githubusercontent.com/senti-platform/senti-client-setup/master/setup | sudo -E bash
# sudo curl -sL https://raw.githubusercontent.com/senti-platform/senti-client-setup/master/setup | sudo -E bash

clear

# Login
sudo -i

echo Setting up Senti-MQTT-Client

# Create temporary tools work directory
sudo mkdir -p /usr/local/tools
cd /usr/local/tools
pwd

# Install all needed helper software
# Check if needed software exist
echo
echo Checking if needed software is installed ... 

GIT=/usr/bin/git
if [ ! -e "$GIT" ]; then
	echo
    echo "git is not installed."
	echo "Installing git ..."
	sudo apt install git-all
	git --version
else 
    echo "git is already installed"
fi 

NODE=/usr/local/bin/node
if [ ! -e "$NODE" ]; then
	echo
    echo "nodejs is not installed."
	echo "Installing nodejs & npm ..."
	echo
	sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash && sudo apt-get install -y nodejs && sudo apt-get install build-essential
	echo
	node -v
	npm -v
else 
    echo "nodejs is already installed"
	echo
	node -v
	npm -v
fi

MQTT=/usr/local/bin/mqtt
if [ ! -e "$MQTT" ]; then
	echo
    echo "MQTT is not installed."
	echo "Installing MQTT ..."
	sudo npm install mqtt -g
	mqtt version
else 
    echo "MQTT is already installed"
	mqtt version
fi

# Create paths
sudo mkdir -p /srv/nodejs/senti

echo 
echo Fetching latest versions of Senti software from GitHub
cd /srv/nodejs/senti
sudo git -C senti-mqtt-client pull || git clone https://github.com/senti-platform/senti-mqtt-client.git
sudo git -C senti-watchman pull || git clone https://github.com/senti-platform/senti-watchman.git
echo 

echo Installing modules and/or upgrades
echo
cd /srv/nodejs/senti/senti-mqtt-client
sudo npm install
echo
sudo mkdir -p /srv/nodejs/senti/senti-mqtt-client/logs
cd /srv/nodejs/senti/senti-watchman
sudo npm install
echo
echo
echo Starting senti-mqtt-client service ...
echo

